// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: "https://blenx-dev.github.io",

	base: "/blenx-auth/",
	integrations: [
		starlight({
			title: 'Blenx Auth - Docs',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			// https://starlight.astro.build/guides/sidebar/#autogenerated-links
		sidebar: [
			{
				label: 'Getting Started',
				items: [{ autogenerate: { directory: 'getting-started' } }],
			},
			{
				label: 'Core Concepts',
				items: [{ autogenerate: { directory: 'core-concepts' } }],
			},
			{
				label: 'Adapters',
				items: [{ autogenerate: { directory: 'adapters' } }],
			},
			{
				label: 'FastAPI',
				items: [{ autogenerate: { directory: 'fastapi' } }],
			},
			{
				label: 'Token Strategies',
				items: [{ autogenerate: { directory: 'token-strategies' } }],
			},
			{
				label: 'Advanced',
				items: [{ autogenerate: { directory: 'advanced' } }],
			},
			{
				label: 'Examples',
				items: [{ autogenerate: { directory: 'examples' } }],
			},
			{
				label: 'Reference',
				items: [{ autogenerate: { directory: 'reference' } }],
			},
			{
				// Autogenerate links for the root-level pages (index, ABSTRACTS, etc.).
				autogenerate: { directory: '.' },
			},
		],
		}),
	],
});
